apiVersion: apps/v1  #API library of Kubernetes app/v1 or v1
kind: Deployment # What we want to apply to Kubernetes cluster like Pod, Deployment, Service etc.
metadata: #information regarding the deployment
  name: naveenaws
  labels:  #most important to idetify deployment in a cluster
    app: web
spec: #specification section for Deployment.
  replicas: 3 # number of replicas for load balancing / fault tolerance
  selector: # Selector block to match the label of Deployment with the underlying pod
   matchLabels:
    app: web # this label should be same for both Deployment and Pod definition
  template: #this template section is for the pod definition within a deployment
   metadata: 
    name: naveenaws
    labels:
     app: web
   spec: # specification section for Pod.
    containers: # Container definition. 
     - name: naveenaws
       image: rsoftsysadmin/awswebsite
    