apiVersion: v1 
kind: Service 
metadata:
  name: awsservice
  labels:
    app: web
spec: 
   selector: # this selector should match with the labels of the Deployment file for Endpoint mapping.
     app: web
   type: NodePort # Type of service Nodeport or ClusterIP.
   ports:
     - port: 80
       targetPort: 80
       nodePort: 32000

    