apiVersion: v1 
kind: Service 
metadata:
  name: awsservice
  labels:
    app: web
spec: 
   selector:
     app: web
   type: NodePort
   ports:
     - port: 80
       targetPort: 80
       nodePort: 32000

    