apiVersion: apps/v1
kind: Deployment 
metadata:
  name: relipaydeploy
  labels:
    app: relipay
spec:
  replicas: 3
  selector:
    matchLabels:
     app: relipay
  template:
     metadata:
       name: relipaypod
       labels:
         app: relipay
     spec:
       containers:
       - name: relipay
         image: rsoftsysadmin/relipay
         ports:
           - containerPort: 3000

    