apiVersion: v1 
kind: Service
metadata:
  name: relipayservice
  labels:
    app: relipay
spec:
  type: NodePort
  selector:
    app: relipay
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32001