apiVersion: v1
kind: Service
metadata:
  name: testappservice
spec:
  type: NodePort #type of service defined: ClusterIP(default), Nodeport, Ingress etc.
  selector:
    name: test_app #label of the Pod in Pod Definition file
  ports:
  - port: 80 #Port on a container
    targetPort: 80 #Port on a Pod
    nodePort: 31000 #Port on the host maching where external users access the website
