apiVersion: v1 
kind: Service
metadata:
  name: tomcatservice
  labels:
    app: tomcat
spec:
  selector:
    app: tomcat
  type: NodePort
  ports:
      - port: 8080
        targetPort: 8080
        nodePort: 30000

  