apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcatdeployment
  labels:
    app: tomcat
spec:
   selector:
    matchLabels:
      app: tomcat 
   template:
    metadata:
      name: tomcatpod
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcatcontainer
          image: tomcat 
          ports:
            - containerPort: 8080
      